### ISSUE TITLE
车牌识别训练问题

### ISSUE THREAD

**Issue by armdebugger** [yuqj1991/caffe_train#13]
我想用 ccpd 数据训练,   请教:
1) 如何生成训练数据?
     examples/licensePlate/prototxt/ResNet_LSTM_CTC/lp_rec_train.prototxt   使用的数据格式是 lmdb,  使用tools/convert_imageset, 发现不能支持多标签;  采用支持多标签的convert_imageset生成lmdb,   训练的时候提示label 错
     也尝试了 examples/licensePlate/scripts 目录下的 脚本,  遇到各种错误
     想知道如何生成训练数据

2)  ResNet_CTC 训练模型
    caffe_train/examples/licensePlate/net/ResNet_CTC/ 目录只有 deploy.txt ,  找不到训练模型
    请问能公开训练模型吗?

**Comment by yuqj1991** [comment]
> 我想用 ccpd 数据训练, 请教:
> 
> 1. 如何生成训练数据?
>    examples/licensePlate/prototxt/ResNet_LSTM_CTC/lp_rec_train.prototxt   使用的数据格式是 lmdb,  使用tools/convert_imageset, 发现不能支持多标签;  采用支持多标签的convert_imageset生成lmdb,   训练的时候提示label 错
>    也尝试了 examples/licensePlate/scripts 目录下的 脚本,  遇到各种错误
>    想知道如何生成训练数据
> 2. ResNet_CTC 训练模型
>    caffe_train/examples/licensePlate/net/ResNet_CTC/ 目录只有 deploy.txt ,  找不到训练模型
>    请问能公开训练模型吗?

问题1:我使用的是ccpd，需要先转换为xml形式的annotation的标注形式，再使用脚本
问题2:模型不方便公开
