### ISSUE TITLE
用自己的数据训练 Centerface_v2_train.prototxt 出错

### ISSUE THREAD

**Issue by popper09** [yuqj1991/caffe_train#14]
![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)

出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。

**Comment by yuqj1991** [comment]
从报错的地方看，是程序没有读进去groundtruth.centernetface的数据格式，是lmdb的，带有landmarks的，你要是不带有landmarks，需要修改prototxt，和网络的最后输出

**Comment by yuqj1991** [comment]
> ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> 
> 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。

/home/yuqianjin/workspace/FH_RT_V2.1.2_20191225/app/demo/video_demo/build.log

**Comment by yuqj1991** [comment]
> ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> 
> 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。

从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下

**Comment by popper09** [comment]
> > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> 
> 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下

数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直读取 label

**Comment by yuqj1991** [comment]
> > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > 
> > 
> > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> 
> 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label

你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？

**Comment by popper09** [comment]
> > > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > > 
> > > 
> > > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> > 
> > 
> > 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label
> 
> 你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？

不会吧，我生成的 lmdb 用在自己的caffe annoteData 层中是可以的，您看看是不是还需要修改其他地方。我把网络数据头 prototxt 的数据头 lm 改为 false 还有最后您的 loss 层也都该为了 false

**Comment by popper09** [comment]
> > > > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > > > 
> > > > 
> > > > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> > > 
> > > 
> > > 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label
> > 
> > 
> > 你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？
> 
> 不会吧，我生成的 lmdb 用在自己的caffe annoteData 层中是可以的，您看看是不是还需要修改其他地方。我把网络数据头 prototxt 的数据头 lm 改为 false 还有最后您的 loss 层也都该为了 false

后来我把网络中其他的层都去掉了，只用了数据层，结果还是一样。

**Comment by yuqj1991** [comment]
如果你只保留了数据层，还是有问题，那可以百分百断定你的数据的label处理方式右问题啊。。。。我的这个就是voc数据格式

**Comment by yuqj1991** [comment]
> > > > > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > > > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > > > > 
> > > > > 
> > > > > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> > > > 
> > > > 
> > > > 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label
> > > 
> > > 
> > > 你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？
> > 
> > 
> > 不会吧，我生成的 lmdb 用在自己的caffe annoteData 层中是可以的，您看看是不是还需要修改其他地方。我把网络数据头 prototxt 的数据头 lm 改为 false 还有最后您的 loss 层也都该为了 false
> 
> 后来我把网络中其他的层都去掉了，只用了数据层，结果还是一样。

如果你只保留了数据层，还是有问题，那可以百分百断定你的数据的label处理方式右问题啊。。。。我的这个就是voc数据格式

**Comment by popper09** [comment]
> > > > > > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > > > > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > > > > > 
> > > > > > 
> > > > > > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> > > > > 
> > > > > 
> > > > > 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label
> > > > 
> > > > 
> > > > 你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？
> > > 
> > > 
> > > 不会吧，我生成的 lmdb 用在自己的caffe annoteData 层中是可以的，您看看是不是还需要修改其他地方。我把网络数据头 prototxt 的数据头 lm 改为 false 还有最后您的 loss 层也都该为了 false
> > 
> > 
> > 后来我把网络中其他的层都去掉了，只用了数据层，结果还是一样。
> 
> 如果你只保留了数据层，还是有问题，那可以百分百断定你的数据的label处理方式右问题啊。。。。我的这个就是voc数据格式

我保证数据没有问题，因为我用其他的 caffe 框架训练，也用的 annotedData 这个数据层，是没有问题的

**Comment by popper09** [comment]
> > > > > > > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > > > > > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > > > > > > 
> > > > > > > 
> > > > > > > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> > > > > > 
> > > > > > 
> > > > > > 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label
> > > > > 
> > > > > 
> > > > > 你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？
> > > > 
> > > > 
> > > > 不会吧，我生成的 lmdb 用在自己的caffe annoteData 层中是可以的，您看看是不是还需要修改其他地方。我把网络数据头 prototxt 的数据头 lm 改为 false 还有最后您的 loss 层也都该为了 false
> > > 
> > > 
> > > 后来我把网络中其他的层都去掉了，只用了数据层，结果还是一样。
> > 
> > 
> > 如果你只保留了数据层，还是有问题，那可以百分百断定你的数据的label处理方式右问题啊。。。。我的这个就是voc数据格式
> 
> 我保证数据没有问题，因为我用其他的 caffe 框架训练，也用的 annotedData 这个数据层，是没有问题的

我调试最后loss 层取标签的batch id 一直都为 -1

**Comment by yuqj1991** [comment]
> > > > > > > > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > > > > > > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> > > > > > > 
> > > > > > > 
> > > > > > > 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label
> > > > > > 
> > > > > > 
> > > > > > 你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？
> > > > > 
> > > > > 
> > > > > 不会吧，我生成的 lmdb 用在自己的caffe annoteData 层中是可以的，您看看是不是还需要修改其他地方。我把网络数据头 prototxt 的数据头 lm 改为 false 还有最后您的 loss 层也都该为了 false
> > > > 
> > > > 
> > > > 后来我把网络中其他的层都去掉了，只用了数据层，结果还是一样。
> > > 
> > > 
> > > 如果你只保留了数据层，还是有问题，那可以百分百断定你的数据的label处理方式右问题啊。。。。我的这个就是voc数据格式
> > 
> > 
> > 我保证数据没有问题，因为我用其他的 caffe 框架训练，也用的 annotedData 这个数据层，是没有问题的
> 
> 我调试最后loss 层取标签的batch id 一直都为 -1

我不知道你的问题出在哪里，不用考虑后面loss层，如果你只保留数据层，都读不到label，那后面就不用测试了，至于问题出在哪，我这边不知道。label的读取方式并没有什么特别。

**Comment by popper09** [comment]
> > > > > > > > > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > > > > > > > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label
> > > > > > > 
> > > > > > > 
> > > > > > > 你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？
> > > > > > 
> > > > > > 
> > > > > > 不会吧，我生成的 lmdb 用在自己的caffe annoteData 层中是可以的，您看看是不是还需要修改其他地方。我把网络数据头 prototxt 的数据头 lm 改为 false 还有最后您的 loss 层也都该为了 false
> > > > > 
> > > > > 
> > > > > 后来我把网络中其他的层都去掉了，只用了数据层，结果还是一样。
> > > > 
> > > > 
> > > > 如果你只保留了数据层，还是有问题，那可以百分百断定你的数据的label处理方式右问题啊。。。。我的这个就是voc数据格式
> > > 
> > > 
> > > 我保证数据没有问题，因为我用其他的 caffe 框架训练，也用的 annotedData 这个数据层，是没有问题的
> > 
> > 
> > 我调试最后loss 层取标签的batch id 一直都为 -1
> 
> 我不知道你的问题出在哪里，不用考虑后面loss层，如果你只保留数据层，都读不到label，那后面就不用测试了，至于问题出在哪，我这边不知道。label的读取方式并没有什么特别。

我都快疯了

**Comment by yuqj1991** [comment]
> > > > > > > > > > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > > > > > > > > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？
> > > > > > > 
> > > > > > > 
> > > > > > > 不会吧，我生成的 lmdb 用在自己的caffe annoteData 层中是可以的，您看看是不是还需要修改其他地方。我把网络数据头 prototxt 的数据头 lm 改为 false 还有最后您的 loss 层也都该为了 false
> > > > > > 
> > > > > > 
> > > > > > 后来我把网络中其他的层都去掉了，只用了数据层，结果还是一样。
> > > > > 
> > > > > 
> > > > > 如果你只保留了数据层，还是有问题，那可以百分百断定你的数据的label处理方式右问题啊。。。。我的这个就是voc数据格式
> > > > 
> > > > 
> > > > 我保证数据没有问题，因为我用其他的 caffe 框架训练，也用的 annotedData 这个数据层，是没有问题的
> > > 
> > > 
> > > 我调试最后loss 层取标签的batch id 一直都为 -1
> > 
> > 
> > 我不知道你的问题出在哪里，不用考虑后面loss层，如果你只保留数据层，都读不到label，那后面就不用测试了，至于问题出在哪，我这边不知道。label的读取方式并没有什么特别。
> 
> 我都快疯了

我觉得你可以顺着代码查一查，你说的box为0,numbboxes会发生变化的地方
![image](https://user-images.githubusercontent.com/38523749/89528587-e40e1200-d81d-11ea-8cf3-14c7f15670de.png)
在这里，具体原因，如果你能进入到if里面，你最好再看看关于数据前处理的这一块

**Comment by popper09** [comment]
> > > > > > > > > > > > ![222](https://user-images.githubusercontent.com/69227743/89365234-c601be00-d706-11ea-8a47-aae364767925.png)
> > > > > > > > > > > > 出错，不知道是哪里的问题，请教一下，看了源码也觉得没有问题；数据的问题也排除了，因为训练自己的Caffe，数据是可用的。
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 从报错的地方来看，程序没有读入groundtruth，数据集是lmdb的，而且这个是带有landmarks的，如果你没有landmarks，是需要在prototxt修改相关landmarks的标志位设为false，而且最后的输出output也要调整一下
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 数据头我设置了 lm 为 false, 但是我在调试您的 annotedData 层中， label 读取的 bbox 数量一直为 0，感觉就是一直没有读取到 label
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 你好，我重新测试了，没有问题。你说的bbox一直为0，可能你生成的lmdb不一样？还是怎样？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不会吧，我生成的 lmdb 用在自己的caffe annoteData 层中是可以的，您看看是不是还需要修改其他地方。我把网络数据头 prototxt 的数据头 lm 改为 false 还有最后您的 loss 层也都该为了 false
> > > > > > > 
> > > > > > > 
> > > > > > > 后来我把网络中其他的层都去掉了，只用了数据层，结果还是一样。
> > > > > > 
> > > > > > 
> > > > > > 如果你只保留了数据层，还是有问题，那可以百分百断定你的数据的label处理方式右问题啊。。。。我的这个就是voc数据格式
> > > > > 
> > > > > 
> > > > > 我保证数据没有问题，因为我用其他的 caffe 框架训练，也用的 annotedData 这个数据层，是没有问题的
> > > > 
> > > > 
> > > > 我调试最后loss 层取标签的batch id 一直都为 -1
> > > 
> > > 
> > > 我不知道你的问题出在哪里，不用考虑后面loss层，如果你只保留数据层，都读不到label，那后面就不用测试了，至于问题出在哪，我这边不知道。label的读取方式并没有什么特别。
> > 
> > 
> > 我都快疯了
> 
> 我觉得你可以顺着代码查一查，你说的box为0,numbboxes会发生变化的地方
> ![image](https://user-images.githubusercontent.com/38523749/89528587-e40e1200-d81d-11ea-8cf3-14c7f15670de.png)
> 在这里，具体原因，如果你能进入到if里面，你最好再看看关于数据前处理的这一块

这里我调试过， anno_datum.annotation_group_size() 为0， 不知道为啥。

**Comment by popper09** [comment]
我把你的 Loss 层添加到自己的 caffe  中可以训练了，谢谢。您的数据头我感觉有问题，虽然不知道哪里的问题。

**Comment by yuqj1991** [comment]
> 我把你的 Loss 层添加到自己的 caffe 中可以训练了，谢谢。您的数据头我感觉有问题，虽然不知道哪里的问题。

你能训练就好，祝你好运

**Comment by cq123456789** [comment]
同样的问题，就是没有lm，使用你的annotation，会读不到标签label（比如用这个去训练目标检测的Voc数据集），我也很疑惑，哎╮(╯▽╰)╭
